### ISSUE TITLE
JOSS Review - References on sampling schme adapation

### ISSUE THREAD

**Issue by rreinecke** [Basvanstein/GSAreport#16]
Reading through the JOSS paper and the Readme of your project I find myself wondering what exactly the added value of your application is. I am not saying it is not there I just don't quite understand why I would not just be using SAlib directly. Also I think you should point out other toolboxes like SAFE.

To be more precise: Please add a little bit more description of what the user explicitly gains from using this software. Be a bit more explicit on how it fits into the world of existing toolboxes out there.

Furthermore, you state that "each method in the original SALib package requires a different sampling scheme and different sample size". Well the sample size is related to convergence and the scheme very much to the underlying methods and has nothing to do with SAlib. Please elaborate what your your tool does exactly. For me this is currently rather confusing.

**Comment by rreinecke** [comment]
https://github.com/openjournals/joss-reviews/issues/4721

**Comment by Basvanstein** [comment]
Dear @rreinecke , happy to explain it more elaborately of course, but I am not sure how to make this concise in the paper.md.

The GSAreport application is different from using SALib directly in a number of ways:

1. The GSAreport application does not require python knowledge (though can be used as python package as well).
2. The GSAreport application uses a surrogate model when only 1 specific sampling scheme is present (for example for expensive industrial applications) to allow other GSA methods to work properly.
3. Many GSA methods require a sampling scheme with a specific number of evaluations in terms of the dimensions (for example x*(d+1) or x*(d+2), this makes it hard to run multiple GSA methods if you are not familiar with these details, GSAreport tries to take this problem away from the user by working around these requirements.
4. The GSAreport application selects a suitable subset of GSA methods based on empirically found rules of thumb, for specifics about this selection I would like to refer to our paper: https://www.techrxiv.org/articles/preprint/A_Comparison_of_Global_Sensitivity_Analysis_Methods_for_Explainable_AI_with_an_Application_in_Genomic_Prediction/20528292
5. The GSAreport application bundles these methods in a readable report with interactive plots showing both first and second order sensitivities, including explanations and references to the different methods.
6. GSAreport also uses graph-tool to visualise first and second order Sobol indices in an intuitive manner.

SAFE is indeed a comparable toolbox but is for Matlab and I have unfortunately no experience with the toolbox and as such I find it difficult to compare it, I can of course add it as a relevant link.
GSAreport is meant for making GSA methods as easy as possible to use and to advice the end-users which methods work well in which situation.
I hope this clarifies the contribution. Do you have any suggestion as to how to incorporate this better in the paper.md?

**Comment by rreinecke** [comment]
Thank you @Basvanstein for the additional explanation! It is much clearer to me now. Why not just integrate this text into the paper? You could add it as subsection to the statement of need.
I think this statement is quite important and I am not sure this message gets through in the current paper version: "GSAreport is meant for making GSA methods as easy as possible to use and to advice the end-users which methods work well in which situation." Please think about revising the text and making it more concise.

SAFE is actually also available in python. And they also provide "workflows" that users can follow to apply the methods in a meaningful way. I agree that this is more applied than your tool but maybe still noteworthy.

Overall I like to add that I really like your project and think this is a valuable addition to the SA community!

**Comment by Basvanstein** [comment]
Thank you very much for the nice comment.
I have updated the paper, for some reason I had in my mind it could be 1 page maximum, but I realise now that that is not the case. If you think the additions to the paper resolve the issue feel free to close it.

**Comment by rreinecke** [comment]
Great! I saw that you have updated the md file in your paper branch. This seems not to have changed the paper generated by the editorial bot. Anyways I am closing this. @Basvanstein Please make sure your changes make it into the final paper.
