### ISSUE TITLE
JOSS review: notes on example usage

### ISSUE THREAD

**Issue by rreinecke** [Basvanstein/GSAreport#18]
- The demo mode on the docker image doesn't seem to work
- Please provide the files necessary to run the example at https://basvanstein.github.io/GSAreport/1.0/usecases It is nicely described but providing the first json file would make it much easier to get started.
- I am a bit confused by the example: you state that the user does not necessary need any python knowledge. But for running the SA in the quickstart you really need to know what you are doing even if it is a simple example. So GSA report is not running the SA for you? It is simplifying the sampling and the analysis but it is not running the experiment. I think that should be clarified in the project and paper description.
- the last line in the quickstart as improper line breaks - a simple copy and paste does not work
- After running the Qucikstart it provides me with the output: "Created a graph with 3 vertices and 1 edges.
Vertices are the top 5 ST values greater than 0.01.
Only S2 values (edges) greater than 0.0 are included." ok well, what does that tell me? The output folder is empty. How do I get the graphical report?

**Comment by Basvanstein** [comment]
> * The demo mode on the docker image doesn't seem to work

What did you try exactly? It is important that when running Docker we also create a volume and specify the output path such that we see the generated files.
For example the following command:

```
#on linux:
docker run --rm -v `pwd`/output:/output ghcr.io/basvanstein/gsareport:main --demo -o /output

#on windows:
docker run --rm -v $pwd/output:/output ghcr.io/basvanstein/gsareport:main --demo -o /output
```

Runs the docker image with the "output" directory (of the current working directory) as a volume linked to the docker "/output" folder. The `-o /output` tells the program to store the resulting report in the output directory.  
After this run you should see an html report in the output directory appear.

> * Please provide the files necessary to run the example at https://basvanstein.github.io/GSAreport/1.0/usecases It is nicely described but providing the first json file would make it much easier to get started.

The example files including the `problem.json` can be found in the `data` directory.

> * I am a bit confused by the example: you state that the user does not necessary need any python knowledge. But for running the SA in the quickstart you really need to know what you are doing even if it is a simple example. So GSA report is not running the SA for you? It is simplifying the sampling and the analysis but it is not running the experiment. I think that should be clarified in the project and paper description.

GSAreport is not running the evaluation (what you call experiment) of the real function / model you want to analyse. This is on purpose to make it flexible as the thing you want to analyse could be an R model, python ML model, executable etc. etc.
GSAreport provides 2 of the 3 steps, generating the required sample schemes (if you do not use a custom scheme) and running the SA algorithms to generate a report. I thought it was well described but I can add some sentences to put more emphasis on this aspect.

> * the last line in the quickstart as improper line breaks - a simple copy and paste does not work

Will check, which terminal do you use? It was written for Linux/mac and works slightly different for powershell for example (I can add a tab for windows as well)

> * After running the Qucikstart it provides me with the output: "Created a graph with 3 vertices and 1 edges.
>   Vertices are the top 5 ST values greater than 0.01.
>   Only S2 values (edges) greater than 0.0 are included." ok well, what does that tell me? The output folder is empty. How do I get the graphical report?

If you use a volume and set the output parameter of the program correctly it should generate a report inside the folder. If it does not appear it is likely that it generated the report in a folder you do not have a docker volume to. This could be related to your terminal environment as well. For example the last command from the quickstart (which you can run on the sample data as well) is for windows powershell:

```
docker run --rm -v $pwd/output:/output -v $pwd/data:/data ghcr.io/basvanstein/gsareport:main -p /data/problem.json -d /data -o /output
```

Hope this helps, let me know what terminal/OS you use that way I can provide more detailed instructions. I will also try to include these differences in the Documentation.

**Comment by rreinecke** [comment]
> docker run --rm -v `pwd`/output:/output ghcr.io/basvanstein/gsareport:main --demo -o /output

The command works. But the output folder is empty. Also as a Linux user I expect "/output" to write something to root/output. It would be better to just write "output" without the "/". 

> The example files including the problem.json can be found in the data directory.
Then point the user to that file in the documentation. How should I know that?

> GSAreport is not running the evaluation (what you call experiment) of the real function / model you want to analyse.
Maybe you could add a flow chart diagram to the documentation to make clear what the typical workflow is. And yes please state it clearly in the paper.

> Will check, which terminal do you use? It was written for Linux/mac and works slightly different for powershell for example (I can add a tab for windows as well)
I am using the standard Gnome terminal. All other commands did work with copy paste except for this one.

> windows powershell:
This then likely explains a lot ... could you please provide me with the correct command to that I can test that on a proper OS.
Please also state that in the user guide.

**Comment by Basvanstein** [comment]
> > docker run --rm -v `pwd`/output:/output ghcr.io/basvanstein/gsareport:main --demo -o /output
> 
> The command works. But the output folder is empty. Also as a Linux user I expect "/output" to write something to root/output. It would be better to just write "output" without the "/".

Sorry but this is actually related to Docker knowledge and not the tool, it definitely points to the output folder in the root, but the root is the root of the Docker container which is linked via a volume to the output folder of the current working directory.
Hard to say why the output folder is empty in your case since I tested this on 3 different machines and for all 3 it worked, Ubuntu, Mac and Windows. Perhaps you did not give Docker permission to access your drive? I believe this issue is Docker related and not related to the actual application we propose. Perhaps instead you can try to run the python library instead which is easy to install on linux.
> 
> > The example files including the problem.json can be found in the data directory.
> 
> Then point the user to that file in the documentation. How should I know that?

It states in the documentation "To start, you always need to provide the program with a problem definition. This definition can be supplied as json file, see also data/problem.json"  
Perhaps you read over it, I can make it more clear by repeating it in the data section.
> 
> > GSAreport is not running the evaluation (what you call experiment) of the real function / model you want to analyse.
> 
> Maybe you could add a flow chart diagram to the documentation to make clear what the typical workflow is. And yes please state it clearly in the paper.

Good idea, will do that.
> 
> > Will check, which terminal do you use? It was written for Linux/mac and works slightly different for powershell for example (I can add a tab for windows as well)
> 
> I am using the standard Gnome terminal. All other commands did work with copy paste except for this one.
> 
Thanks will check with Gnome.

> > windows powershell:
> 
> This then likely explains a lot ... could you please provide me with the correct command to that I can test that on a proper OS. Please also state that in the user guide.

For Linux that should be 
```
docker run --rm -v `pwd`/output:/output -v `pwd`/data:/data ghcr.io/basvanstein/gsareport:main -p /data/problem.json -d /data -o /output
```

**Comment by rreinecke** [comment]
> For Linux that should be

Well that did work! I don't know why this did not work for the demo mode then.
