### ISSUE TITLE
[REVIEW]: GSAreport: Easy to Use Global Sensitivity Reporting

### ISSUE THREAD

**Issue by Saran-nns** [Basvanstein/GSAreport#22]
Hi @Basvanstein and sorry for the late review,

Here are few suggestions and requests,

- [x] Numpy version conflict between gsareport and shap (Numpy version should be < = 1.20), may need to update requirements.txt at the src.
- [x] Readme is too informative. The "installation instructions" and the " usage" sections are the same in github readme and in the documentation. It would be more convenient to follow the readme if it contains the highly recommended installation/usage and hyperlinks(documentation) for the others, including the 'Building binaries (for developers)' section.
- [x] How about some example analysis images/gifs (e.g. headmaps, correlation analysis) in the introduction section of the readme.
- [x] References in the paper and in the readme have different citation styles.  [Citation syntax](https://pandoc.org/MANUAL.html#extension-citations)
- [x] It is not required, but I suggest test coverage in the actions. E.g. the plot functions are not included in the automated test.

Let me know what you think of these suggestions.

**Comment by Basvanstein** [comment]
Thank you for the comments!  
I will check and update the numpy conflict, we can just take the shap version and remove it in the requirements.  
Good point about the readme, will clean it up a bit and will add some example images.

I used the citation syntax that the packages themselves provided, the paper uses a bibtex file, so I guess the style there is standardized no? Will check and update.

Plot functions are not that useful to automatically test I think, running the demo and checking the output basically shows that they are all working. In the tests I could check if the files exist but I don't think that it adds much. The rest of the functions is covered.

**Comment by Basvanstein** [comment]
I have updated the readme and made it more clear for developers, pointing to the documentation to avoid duplication.

I have fixed the paper bibtex and citation style and resolved the numpy version conflict.

Hope you like it :)

**Comment by Basvanstein** [comment]
Indeed, well spotted. Moved the References section to the end and called that section Related software.
